# Generated by Django 5.1.1 on 2024-09-08 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0001_initial'),
        ('patients', '0002_alter_patient_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='end_prescription_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insurance_policy_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='start_prescription_date',
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance_provider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='insurances.insurance'),
        ),
    ]
