# Generated by Django 5.1.1 on 2024-09-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patient_end_prescription_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='primary_care_physician',
        ),
    ]
