# Generated by Django 5.1.1 on 2024-11-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='department',
            field=models.CharField(blank=True, choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('oncology', 'Oncology'), ('pediatrics', 'Pediatrics'), ('surgery', 'Surgery'), ('anesthesiology', 'Anesthesiology'), ('dermatology', 'Dermatology'), ('emergency_medicine', 'Emergency Medicine'), ('endocrinology', 'Endocrinology'), ('gastroenterology', 'Gastroenterology'), ('gynecology', 'Gynecology'), ('hematology', 'Hematology'), ('infectious_disease', 'Infectious Disease'), ('nephrology', 'Nephrology'), ('obstetrics', 'Obstetrics'), ('orthopedics', 'Orthopedics'), ('otolaryngology', 'Otolaryngology (ENT)'), ('pathology', 'Pathology'), ('psychiatry', 'Psychiatry'), ('pulmonology', 'Pulmonology'), ('radiology', 'Radiology'), ('rheumatology', 'Rheumatology'), ('urology', 'Urology'), ('vascular_surgery', 'Vascular Surgery'), ('plastic_surgery', 'Plastic Surgery')], help_text='Department where the patient is located if hospitalized', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='room_number',
            field=models.CharField(blank=True, help_text='Room number for the patient if hospitalized', max_length=10, null=True),
        ),
    ]
