# Generated by Django 5.1.1 on 2024-09-08 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prescription',
            table='prescriptions',
        ),
    ]
