# Generated by Django 5.1.1 on 2024-10-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='department',
            field=models.CharField(blank=True, choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('oncology', 'Oncology'), ('pediatrics', 'Pediatrics'), ('surgery', 'Surgery'), ('anesthesiology', 'Anesthesiology'), ('dermatology', 'Dermatology'), ('emergency_medicine', 'Emergency Medicine'), ('endocrinology', 'Endocrinology'), ('gastroenterology', 'Gastroenterology'), ('gynecology', 'Gynecology'), ('hematology', 'Hematology'), ('infectious_disease', 'Infectious Disease'), ('nephrology', 'Nephrology'), ('obstetrics', 'Obstetrics'), ('orthopedics', 'Orthopedics'), ('otolaryngology', 'Otolaryngology (ENT)'), ('pathology', 'Pathology'), ('psychiatry', 'Psychiatry'), ('pulmonology', 'Pulmonology'), ('radiology', 'Radiology'), ('rheumatology', 'Rheumatology'), ('urology', 'Urology'), ('vascular_surgery', 'Vascular Surgery'), ('plastic_surgery', 'Plastic Surgery')], max_length=50, null=True),
        ),
    ]
