# Generated by Django 5.1.1 on 2024-10-08 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0002_alter_nurse_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number can only contain digits and the characters ()[] .-* /', regex='^[0-9\\(\\)\\[\\]\\.\\-\\*\\/]+$')]),
        ),
    ]
