# Generated by Django 5.1.1 on 2024-10-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0003_alter_nurse_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Other', 'Other')], default='Other', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nurse',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
