# Generated by Django 5.1.1 on 2024-10-11 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0004_nurse_gender_alter_nurse_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurse',
            old_name='supervised_nurses',
            new_name='supervisor_nurses',
        ),
    ]
