# Generated by Django 5.1.1 on 2024-10-11 03:57
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0005_rename_supervised_nurses_nurse_supervisor_nurses'),
    ]
    operations = [
        migrations.AddField(
            model_name='nurse',
            name='hiring_end_date',
            field=models.DateField(null=True, blank=True),
            preserve_default=False,
        ),
    ]
