# Generated by Django 5.1.1 on 2024-09-08 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emergencycontact',
            table='emergency_contacts',
        ),
    ]
