# Generated by Django 5.1.1 on 2024-10-19 13:17

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_contacts', '0003_alter_emergencycontact_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencycontact',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='email',
            field=models.EmailField(default='default@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Other', 'Other')], default='O', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='last_name',
            field=models.CharField(default='DefaultLastName', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone_number',
            field=models.CharField(default=111111111, max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number can only contain digits and the characters ()[] .-* /', regex='^[0-9\\(\\)\\[\\]\\.\\-\\*\\/]+$')]),
            preserve_default=False,
        ),
    ]
