# Generated by Django 5.1.1 on 2024-10-19 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_contacts', '0004_rename_name_emergencycontact_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencycontact',
            old_name='mobile_phone_number',
            new_name='secondary_phone_number',
        ),
    ]
