# Generated by Django 5.1.1 on 2024-10-19 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_contacts', '0005_rename_mobile_phone_number_emergencycontact_secondary_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='secondary_phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number can only contain digits and the characters ()[] .-* /', regex='^[0-9\\(\\)\\[\\]\\.\\-\\*\\/]+$')]),
        ),
    ]
