DEPARTMENT_CHOICES = [
    ('cardiology', 'Cardiology'),
    ('neurology', 'Neurology'),
    ('oncology', 'Oncology'),
    ('pediatrics', 'Pediatrics'),
    ('surgery', 'Surgery'),
    ('anesthesiology', 'Anesthesiology'),
    ('dermatology', 'Dermatology'),
    ('emergency_medicine', 'Emergency Medicine'),
    ('endocrinology', 'Endocrinology'),
    ('gastroenterology', 'Gastroenterology'),
    ('gynecology', 'Gynecology'),
    ('hematology', 'Hematology'),
    ('infectious_disease', 'Infectious Disease'),
    ('nephrology', 'Nephrology'),
    ('obstetrics', 'Obstetrics'),
    ('orthopedics', 'Orthopedics'),
    ('otolaryngology', 'Otolaryngology (ENT)'),
    ('pathology', 'Pathology'),
    ('psychiatry', 'Psychiatry'),
    ('pulmonology', 'Pulmonology'),
    ('radiology', 'Radiology'),
    ('rheumatology', 'Rheumatology'),
    ('urology', 'Urology'),
    ('vascular_surgery', 'Vascular Surgery'),
    ('plastic_surgery', 'Plastic Surgery'),
]

APP_LOGER = 'hospital_management_system_logger'
