# Generated by Django 5.1.1 on 2024-09-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_table'),
        ('patients', '0004_remove_patient_primary_care_physician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(null=True, related_name='doctors', to='patients.patient'),
        ),
    ]
