# Generated by Django 5.1.1 on 2024-09-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_patients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('GP', 'General Practitioner'), ('Cardiologist', 'Cardiologist'), ('Neurologist', 'Neurologist'), ('Dermatologist', 'Dermatologist'), ('Radiologist', 'Radiologist'), ('Pediatrician', 'Pediatrician'), ('Oncologist', 'Oncologist'), ('Orthopedist', 'Orthopedist'), ('Ophthalmologist', 'Ophthalmologist'), ('Psychiatrist', 'Psychiatrist'), ('Endocrinologist', 'Endocrinologist'), ('Rheumatologist', 'Rheumatologist'), ('Gastroenterologist', 'Gastroenterologist'), ('Nephrologist', 'Nephrologist'), ('Pulmonologist', 'Pulmonologist'), ('Urologist', 'Urologist'), ('Hematologist', 'Hematologist'), ('Anesthesiologist', 'Anesthesiologist'), ('Plastic Surgeon', 'Plastic Surgeon'), ('Obstetrician', 'Obstetrician'), ('Gynecologist', 'Gynecologist')], max_length=50),
        ),
    ]
