# Generated by Django 5.1.1 on 2024-09-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctor_specialty'),
        ('patients', '0004_remove_patient_primary_care_physician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(related_name='doctors', to='patients.patient'),
        ),
    ]
